package net.ksripairojn.geologyredefined.block;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.ksripairojn.geologyredefined.GeologyRedefined;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registry;
import net.minecraft.registry.Registries;

import net.minecraft.util.Identifier;

public class ModBlocks {
    public static final Block BLOCK_OF_OLIVINE = registerBlock("block_of_olivine",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_PYROXENE = registerBlock("block_of_pyroxene",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_AMPHIBOLE = registerBlock("block_of_amphibole",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_MUSCOVITE = registerBlock("block_of_muscovite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_BIOTITE = registerBlock("block_of_biotite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_ANORTHITE = registerBlock("block_of_anorthite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_ALBITE = registerBlock("block_of_albite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_ORTHOCLASE = registerBlock("block_of_orthoclase",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_LABRADORITE = registerBlock("block_of_labradorite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_SMOKY_QUARTZ = registerBlock("block_of_smoky_quartz",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_ROSE_QUARTZ = registerBlock("block_of_rose_quartz",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_OPAL = registerBlock("block_of_opal",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_PYROPE = registerBlock("block_of_pyrope",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_UVAROVITE = registerBlock("block_of_uvarovite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_BLUE_ZIRCON = registerBlock("block_of_blue_zircon",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_RED_ZIRCON = registerBlock("block_of_red_zircon",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_KYANITE = registerBlock("block_of_kyanite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_EPIDOTE = registerBlock("block_of_epidote",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_YELLOW_TOPAZ = registerBlock("block_of_yellow_topaz",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_TURQUOISE = registerBlock("block_of_turquoise",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_CALCITE = registerBlock("block_of_calcite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_AZURITE = registerBlock("block_of_azurite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_MALACHITE = registerBlock("block_of_malachite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_BLACK_TOUR = registerBlock("block_of_black_prismatic_tourmaline",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_WATER_TOUR = registerBlock("block_of_watermelon_tourmaline",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_GOETHITE = registerBlock("block_of_goethite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_BAUXITE = registerBlock("block_of_bauxite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_PYRITE = registerBlock("block_of_pyrite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_PYRITEWGOE = registerBlock("block_of_pyrite_with_goethite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_GALENA = registerBlock("block_of_galena",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_FLUORITE = registerBlock("block_of_fluorite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_SYLVITE = registerBlock("block_of_sylvite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_GYPSUM = registerBlock("block_of_gypsum",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_SULFUR = registerBlock("block_of_sulfur",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_MAGNETITE = registerBlock("block_of_magnetite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_MAGNETITEWGOE = registerBlock("block_of_magnetite_with_goethite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_SPINEL = registerBlock("block_of_spinel",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BLOCK_OF_SALT = registerBlock("block_of_salt",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block DUNITE = registerBlock("dunite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block PERIDOTITE = registerBlock("peridotite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block PYROXENITE = registerBlock("pyroxenite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block KOMATIITE = registerBlock("komatiite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block GABBRO = registerBlock("gabbro",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block BASALT = registerBlock("basalt",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block GRANITE = registerBlock("granite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block DIORITE = registerBlock("diorite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block ANDESITE = registerBlock("andesite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SCORIA = registerBlock("scoria",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block PUMICE = registerBlock("pumice",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block APLITE = registerBlock("aplite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block RHYOLITE = registerBlock("rhyolite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block CONGLOMERATE = registerBlock("conglomerate",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SANDSTONE = registerBlock("sandstone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SILTSTONE = registerBlock("siltstone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SILT = registerBlock("silt",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block MUDSTONE = registerBlock("mudstone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block CLAYSTONE = registerBlock("claystone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block LIMESTONE = registerBlock("limestone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block DOLOSTONE = registerBlock("dolostone",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block TRAVERTINE = registerBlock("travertine",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block DIATOMITE = registerBlock("diatomite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block COQUINA = registerBlock("coquina",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block CHALK = registerBlock("chalk",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SHALE = registerBlock("shale",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SLATE = registerBlock("slate",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block PHYLLITE = registerBlock("phyllite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block SCHIST = registerBlock("schist",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block GNEISS = registerBlock("gneiss",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block MARBLE = registerBlock("marble",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block QUARTZITE = registerBlock("quartzite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));
    public static final Block MIGMATITE = registerBlock("migmatite",new Block(AbstractBlock.Settings.create().strength(4f).requiresTool()));

    private static void registerBlockItem(String name, Block block){
        Registry.register(Registries.ITEM, Identifier.of(GeologyRedefined.MOD_ID,name),new BlockItem(block,new Item.Settings()));
    }

    private static Block registerBlock(String name, Block block){
        registerBlockItem(name ,block);
        return Registry.register(Registries.BLOCK, Identifier.of(GeologyRedefined.MOD_ID,name),block);
    }
    public static void registerModBlocks(){
        GeologyRedefined.LOGGER.info("Registering ModBlocks for"+GeologyRedefined.MOD_ID );

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(entries ->{
            entries.add(ModBlocks.BLOCK_OF_OLIVINE);
            entries.add(ModBlocks.BLOCK_OF_PYROXENE);
            entries.add(ModBlocks.BLOCK_OF_AMPHIBOLE);
            entries.add(ModBlocks.BLOCK_OF_MUSCOVITE);
            entries.add(ModBlocks.BLOCK_OF_BIOTITE);
            entries.add(ModBlocks.BLOCK_OF_ANORTHITE);
            entries.add(ModBlocks.BLOCK_OF_ALBITE);
            entries.add(ModBlocks.BLOCK_OF_ORTHOCLASE);
            entries.add(ModBlocks.BLOCK_OF_LABRADORITE);
            entries.add(ModBlocks.BLOCK_OF_SMOKY_QUARTZ);
            entries.add(ModBlocks.BLOCK_OF_ROSE_QUARTZ);
            entries.add(ModBlocks.BLOCK_OF_OPAL);
            entries.add(ModBlocks.BLOCK_OF_PYROPE);
            entries.add(ModBlocks.BLOCK_OF_UVAROVITE);
            entries.add(ModBlocks.BLOCK_OF_BLUE_ZIRCON);
            entries.add(ModBlocks.BLOCK_OF_RED_ZIRCON);
            entries.add(ModBlocks.BLOCK_OF_KYANITE);
            entries.add(ModBlocks.BLOCK_OF_EPIDOTE);
            entries.add(ModBlocks.BLOCK_OF_YELLOW_TOPAZ);
            entries.add(ModBlocks.BLOCK_OF_TURQUOISE);
            entries.add(ModBlocks.BLOCK_OF_CALCITE);
            entries.add(ModBlocks.BLOCK_OF_AZURITE);
            entries.add(ModBlocks.BLOCK_OF_MALACHITE);
            entries.add(ModBlocks.BLOCK_OF_BLACK_TOUR);
            entries.add(ModBlocks.BLOCK_OF_WATER_TOUR);
            entries.add(ModBlocks.BLOCK_OF_GOETHITE);
            entries.add(ModBlocks.BLOCK_OF_BAUXITE);
            entries.add(ModBlocks.BLOCK_OF_PYRITE);
            entries.add(ModBlocks.BLOCK_OF_GALENA);
            entries.add(ModBlocks.BLOCK_OF_PYRITEWGOE);
            entries.add(ModBlocks.BLOCK_OF_FLUORITE);
            entries.add(ModBlocks.BLOCK_OF_SYLVITE);
            entries.add(ModBlocks.BLOCK_OF_GYPSUM);
            entries.add(ModBlocks.BLOCK_OF_SULFUR);
            entries.add(ModBlocks.BLOCK_OF_MAGNETITE);
            entries.add(ModBlocks.BLOCK_OF_MAGNETITEWGOE);
            entries.add(ModBlocks.BLOCK_OF_SPINEL);
            entries.add(ModBlocks.BLOCK_OF_SALT);
            entries.add(ModBlocks.DUNITE);
            entries.add(ModBlocks.PERIDOTITE);
            entries.add(ModBlocks.PYROXENITE);
            entries.add(ModBlocks.KOMATIITE);
            entries.add(ModBlocks.GABBRO);
            entries.add(ModBlocks.BASALT);
            entries.add(ModBlocks.GRANITE);
            entries.add(ModBlocks.DIORITE);
            entries.add(ModBlocks.ANDESITE);
            entries.add(ModBlocks.SCORIA);
            entries.add(ModBlocks.PUMICE);
            entries.add(ModBlocks.APLITE);
            entries.add(ModBlocks.RHYOLITE);
            entries.add(ModBlocks.CONGLOMERATE);
            entries.add(ModBlocks.SANDSTONE);
            entries.add(ModBlocks.SILTSTONE);
            entries.add(ModBlocks.SILT);
            entries.add(ModBlocks.MUDSTONE);
            entries.add(ModBlocks.CLAYSTONE);
            entries.add(ModBlocks.LIMESTONE);
            entries.add(ModBlocks.DOLOSTONE);
            entries.add(ModBlocks.TRAVERTINE);
            entries.add(ModBlocks.DIATOMITE);
            entries.add(ModBlocks.COQUINA);
            entries.add(ModBlocks.CHALK);
            entries.add(ModBlocks.SHALE);
            entries.add(ModBlocks.SLATE);
            entries.add(ModBlocks.PHYLLITE);
            entries.add(ModBlocks.SCHIST);
            entries.add(ModBlocks.GNEISS);
            entries.add(ModBlocks.MARBLE);
            entries.add(ModBlocks.QUARTZITE);
            entries.add(ModBlocks.MIGMATITE);

        });
    }
}
